language: java

addons:
  sonarcloud:
    organization: "ccbonacci"
#    token:
#      secure: "**************************" # encrypted value of your token
# partie du token mise dans le travis-ci.com

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=ccbonacci_ipi-java-350-ex